

[main]
channel="dev"
deploy_owner_id="5r4MYfFQz9iEzjwHUpc79CwrvXqsh7xUzynkiTUEckxB"
#public_service_ood="5aSixgM1oBicrsUdS3nyKM1MA9AgiMEE2y2qFQ3jTTYB"
public_service_ood="5aSixgLoakUWDzRq3j4EL5rWfqyKkz5tmm2in517zpCf"
